### ISSUE TITLE
Duplicate Advertisements

### ISSUE THREAD

**Issue by king-jam** [fromkeith/gossdp#3]
Can you shed some light on the thought process surrounding the choice to have a 1s and 3s timers in each AdvertisableServer instance. I looked in the SSDP Specification to see if that was required and wanted to know if you encountered any issues that made it an obvious solution to a problem.

The member of the struct:
https://github.com/fromkeith/gossdp/blob/master/ssdp.go#L283

**Comment by fromkeith** [comment]
Long time since I've looked at this code :)

I did use this doc I used as reference: http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf

It does suggest that:

> To advertise its capabilities, a device multicasts a number of discovery messages. Specifically, a root device MUST multicast:  Three discovery messages for the root device. 

Not exactly what is being seen in my code.. but I think that is probably why I have it sending multiple advertises, with a not-so-random delay between them.
I also seem to recall sometimes having packet loss on my wifi network, which I think the multiple advertises helps alleviate. (Though maybe i'm crazy there :) its been awhile)

**Comment by king-jam** [comment]
Ahh ok. I'll dig in a little bit further. I can relate to the packet loss realities of WiFi. Thanks for the prompt reply.
